services:
        pretrain:
                image: nuneslu/pointcontrast:latest
                runtime: nvidia
                volumes: 
                        - $PWD:/home/PointContrast
                        - $PWD/Datasets/:/home/PointContrast/Datasets

